In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5,6])
arr1

array([1, 2, 3, 4, 5, 6])

In [7]:
arr2=np.array([[1,2,3,4,5],[3,5,7,8,9]])

In [8]:
type(arr1)

numpy.ndarray

In [9]:
arr2

array([[1, 2, 3, 4, 5],
       [3, 5, 7, 8, 9]])

In [10]:
type(arr2)

numpy.ndarray

In [13]:
arr3=np.zeros((2,3))

In [14]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr4=np.ones((3,3))

In [16]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
arr5=np.identity(5)

In [18]:
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
arr6=np.arange(10)

In [20]:
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr7=np.arange(4,21)
arr7

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
arr8=np.arange(3,9,2)
arr8

array([3, 5, 7])

In [23]:
a=np.linspace(10,20,10)
a

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [24]:
a1=a.copy()
a1

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [25]:
a2=np.array([[[1,2],[3,4],[5,6],[7,8]]])
a2

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [26]:
a2.shape

(1, 4, 2)

In [ ]:
a3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a3.ndim